"use client";
import {useEffect,useMemo,useState} from "react";
function score(t){const velocity=Math.min(1,(t.volume24h/Math.max(t.liquidityUsd,1))/3);const flow=t.txns24h?Math.min(1,t.buys24h/t.txns24h):0;const activity=Math.min(1,t.txns24h/500);const liq=Math.min(1,t.liquidityUsd/100000);const change=Math.max(0,Math.min(1,(t.priceChange24h+20)/80));return Math.round(100*(.30*velocity+.20*flow+.20*activity+.15*liq+.15*change));}
function tier(s){return s>=80?"A":s>=65?"B":s>=50?"C":"D"}
export default function Home(){
 const[min,setMin]=useState(0),[mode,setMode]=useState("candidates"),[data,setData]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 async function load(){setLoading(true);setError("");try{const r=await fetch("/api/market",{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error||"API error");setData(j.tokens||[])}catch(e){setError(e.message||"Live feed unavailable")}finally{setLoading(false)}}
 useEffect(()=>{load();const id=setInterval(load,30000);return()=>clearInterval(id)},[]);
 const rows=useMemo(()=>data.map(x=>({...x,score:score(x)})).sort((a,b)=>b.score-a.score).filter(x=>x.score>=min),[data,min]);
 return <main className="shell"><header><div><div className="eyebrow">JARVIS AI FACTORY / MEME LAB</div><h1>Research before launch.</h1><p className="sub">Live Solana market discovery, explainable scoring and risk filtering.</p></div><div className="status">● {loading?"SYNCING":"LIVE DATA"}</div></header>
 <section className="hero"><div><span className="pill">LIVE MARKET FEED</span><h2>Real market data. No fake demo candidates.</h2><p>JARVIS now reads live Solana pairs through a server-side market route and refreshes automatically. Scores are research signals, not profit guarantees.</p></div><div className="bigscore"><span>TOP LIVE</span><strong>{rows[0]?.score??"—"}</strong><small>/ 100</small></div></section>
 {error&&<div className="warning">Live feed error: {error}</div>}
 <nav><button className={mode==="candidates"?"active":""} onClick={()=>setMode("candidates")}>Live candidates</button><button className={mode==="method"?"active":""} onClick={()=>setMode("method")}>Scoring</button><button onClick={load}>Refresh</button></nav>
 {mode==="candidates"&&<><section className="controls"><label>Minimum score <b>{min}</b></label><input type="range" min="0" max="90" value={min} onChange={e=>setMin(+e.target.value)}/></section><section className="table"><div className="thead"><span>Token</span><span>Score</span><span>Liquidity</span><span>Vol 24h</span><span>Txns</span><span>Buy</span><span>24h</span></div>{rows.map(t=><div className="row" key={t.pair}><span><b>{t.symbol}</b><small>{t.name} · {t.dex}</small></span><span className={"score s"+tier(t.score)}>{t.score}</span><span>{"$"+Math.round(t.liquidityUsd/1000)+"k"}</span><span>{"$"+Math.round(t.volume24h/1000)+"k"}</span><span>{t.txns24h}</span><span>{t.txns24h?Math.round(t.buys24h/t.txns24h*100):0}%</span><span>{t.priceChange24h.toFixed(1)}%</span></div>)}</section></>}
 {mode==="method"&&<section className="cards">{[["Volume/liquidity","30%","Rewards active markets while capping extreme outliers."],["Buy flow","20%","Measures the balance of buys versus sells."],["Activity","20%","Uses transaction activity as a breadth signal."],["Liquidity","15%","Rewards markets with more usable liquidity."],["Price trend","15%","Uses recent price change only as one component."],["Next layer","NEXT","Wallet concentration, holder growth, creator history and manipulation detection are the next research layer."]].map(([a,b,c])=><article key={a}><span>{b}</span><h3>{a}</h3><p>{c}</p></article>)}</section>}
 <footer>JARVIS MEME LAB · LIVE MARKET RESEARCH · Not financial advice</footer></main>
}